name: Test Suite

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      node-version: 12.x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ env.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.node-version }}-yarn-
          ${{ runner.os }}-yarn-

    - run: yarn install --frozen-lockfile --prefer-offline

    - run: yarn lint

    - run: openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -pass env:pass -d -in config.asc -out src/config.js
      env:
        pass: ${{ secrets.ENCPASS }}

    - run: yarn build -- --max_old_space_size=2048
